Name update
ableat/BatchyMcBatchface pull request #4
Opened 2017-04-20 12:30 UTC by BinaryBeard

2017-04-20 18:25 UTC, egladman requested changes
I think there's a better way of achieving this by looping through an array.

2017-04-20 20:10 UTC, BinaryBeard commented
@egladman, you should fix it!

2017-04-20 21:07 UTC, jalama commented
@BinaryBeard stop whining.

2017-04-21 18:16 UTC, egladman approved these changes

2017-04-21 18:18 UTC, egladman commented
I addressed my concerns in #6

2017-04-21 20:38 UTC, merged